export default [
  {
    Sistema: 'DESEM',
    DescripcionCorta: 'DESEMPLEO',
    DescripcionAmigable: 'Prestación por desempleo',
    CodSistema: 7,
  },
  {
    Sistema: 'PREVI',
    DescripcionCorta: 'PREVISIONALES',
    DescripcionAmigable: 'Previsionales',
    CodSistema: 9,
  },
  {
    Sistema: 'PEUN',
    DescripcionCorta: 'PAGO UNICO',
    DescripcionAmigable: 'Pago único de prestación (matrimonio, nacimiento, adopción)',
    CodSistema: 11,
  },
  {
    Sistema: 'DJTUC',
    DescripcionCorta: 'DEP.JUDICIALES - TUT. CUR',
    DescripcionAmigable: 'Depósito Judicial - Tutor o Curador',
    CodSistema: 12,
  },
  {
    Sistema: 'DJEMB',
    DescripcionCorta: 'DEP.JUDICIALES - EMBARGO',
    DescripcionAmigable: 'Deposito Judicial - Embargo sobre Prestación',
    CodSistema: 13,
  },
  {
    Sistema: 'SUAF',
    DescripcionCorta: 'SISTEMA UNICO AAFF',
    DescripcionAmigable: 'SUAF - Sistema Único de Asignaciones Familiares',
    CodSistema: 14,
  },
  {
    Sistema: 'DJSUC',
    DescripcionCorta: 'DEP.JUDICIALES - SUCESION',
    DescripcionAmigable: 'Depósito judicial - Sucesión',
    CodSistema: 15,
  },
  {
    Sistema: 'BORET',
    DescripcionCorta: 'BONOS - NOV. RETROACTIVOS',
    DescripcionAmigable: 'Pagos Retroactivos originados en Bonos Previsionales',
    CodSistema: 17,
  },
  {
    Sistema: 'PNE',
    DescripcionCorta: 'PROGRAMA NAC. DE EMPLEO',
    DescripcionAmigable: 'Programa Nacional de Empleo',
    CodSistema: 18,
  },
  {
    Sistema: 'CALIQ',
    DescripcionCorta: 'CAPITALIZACION-LIQUIDAC.',
    DescripcionAmigable: 'Liquidacion de Prestaciones del Sistema de Capitalizacion (AFJP)',
    CodSistema: 21,
  },
  {
    Sistema: 'PPR',
    DescripcionCorta: 'PROG.PRIVADOS DE EMPLEO',
    DescripcionAmigable: 'Programas privados de Empleo',
    CodSistema: 22,
  },
  {
    Sistema: 'PJH',
    DescripcionCorta: 'PROGRAMAS DEL MTEYSS',
    DescripcionAmigable: 'Programas del Ministerio de Trabajo',
    CodSistema: 23,
  },
  {
    Sistema: 'SENJU',
    DescripcionCorta: 'SENTENCIAS JUDICIALES',
    DescripcionAmigable: 'Sentencias judiciales',
    CodSistema: 24,
  },
  {
    Sistema: 'PMY',
    DescripcionCorta: 'DER.FAM.INC.SOC-P/MAYORES',
    DescripcionAmigable: 'Derecho Familiar de Inclusion Social - Plan Mayores',
    CodSistema: 25,
  },
  {
    Sistema: 'PNC',
    DescripcionCorta: 'PENSIONES NO CONTRIBU.',
    DescripcionAmigable: 'Pensiones No Contributivas',
    CodSistema: 27,
  },
  {
    Sistema: 'SCF',
    DescripcionCorta: 'SUBSIDIO CONTENCION FLIAR',
    DescripcionAmigable: 'Subsidio de Contención Familiar',
    CodSistema: 32,
  },
  {
    Sistema: 'EF',
    DescripcionCorta: 'SUPLEMENTO EXCEPCIONAL',
    DescripcionAmigable: 'Suplemento Excepcional',
    CodSistema: 35,
  },
  {
    Sistema: 'HF',
    DescripcionCorta: 'AYUDA ECON. HOSP. FRANCES',
    DescripcionAmigable: 'Ayuda económica - Hospital Francés',
    CodSistema: 36,
  },
  {
    Sistema: 'PFLIA',
    DescripcionCorta: 'PROG. FLIAS P/INCLUSION',
    DescripcionAmigable: 'Programa Familias por la Inclusión Social',
    CodSistema: 37,
  },
  {
    Sistema: 'AFJP',
    DescripcionCorta: 'AFJP',
    DescripcionAmigable: 'AFJP',
    CodSistema: 50,
  },
  {
    Sistema: 'PDIPA',
    DescripcionCorta: 'P.DES.INFANTIL-1ROS.A¦OS',
    DescripcionAmigable: 'Programa Desnutricion Infantil - Primeros años',
    CodSistema: 52,
  },
  {
    Sistema: 'RENTA',
    DescripcionCorta: 'CIAS DE SEGURO - RENTAS V',
    DescripcionAmigable: 'Rentas Vitalicias - Compañias de Seguro',
    CodSistema: 58,
  },
  {
    Sistema: 'UVHI',
    DescripcionCorta: 'ASIG UNIVERSAL HIJO',
    DescripcionAmigable: 'Asignación Universal por Hijo',
    CodSistema: 60,
  },
  {
    Sistema: 'LESPR',
    DescripcionCorta: 'LEYES ESPEC.PREVISIONALES',
    DescripcionAmigable: 'Leyes especiales previsionales',
    CodSistema: 70,
  },
  {
    Sistema: 'DGI',
    DescripcionCorta: 'D.G.I.',
    DescripcionAmigable: 'DGI',
    CodSistema: 90,
  },
  {
    Sistema: 'HOGAR',
    DescripcionCorta: 'PROGRAMA HOGARES GARRAFAS',
    DescripcionAmigable: 'Programa Hogares con Garrafa',
    CodSistema: 39,
  },
  {
    Sistema: 'RHIST',
    DescripcionCorta: 'REPHISTORICA',
    DescripcionAmigable: 'Reparación Histórica',
    CodSistema: 216,
  },
  {
    Sistema: 'PROG',
    DescripcionCorta: 'PROG.RESPALDO A ESTUD ARG',
    DescripcionAmigable: 'PROGRESAR - Programa de Respaldo a estudiantes argentinos',
    CodSistema: 62,
  },
  {
    Sistema: 'PRIST',
    DescripcionCorta: 'PROGRAMA INGRESO SOCIAL',
    DescripcionAmigable: 'Programa Ingreso social',
    CodSistema: 64,
  },
]